// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

/// @title IVerifier
/// @notice Interface for different ZK proof verification contracts.
interface IVerifier {
    /// @notice Verifies a proof against a verification key and public inputs.
    /// @param verificationKey The circuit-specific verification key.
    /// @param proof The proof bytes generated by the prover.
    /// @param publicInputs An array of bytes representing the public inputs.
    /// @return success True if the proof is valid, false otherwise.
    function verifyProof(
        bytes calldata verificationKey,
        bytes calldata proof,
        bytes[] calldata publicInputs
    ) external view returns (bool success);
}
